openapi: 3.0.0
info:
  version: '1.0'
  title: Cinema API
  description: Thông tin chi tiết về các Rest API phục vụ cho demo module Thanh toán đặt vé xem phim online của môn phát triển phần mềm hướng dịch vụ.
tags:
  - name: ticket

paths:
  # ------- Ticket micro-service -------------------------------------------------------
  /ticket/check:
    post:
      tags:
        - ticket
      description: |
        Kiểm tra các ghế trong request body với mỗi (id ghế + suất chiếu cụ thể), đã có vé nào chứa thông tin này chưa.<br><br>
        Nếu ít nhất một vé đã chứa thông tin các ghế trong request body, trả về thất bại.Ngược lại trả về thành công.

      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  seat_id:
                    type: integer
                    format: int32
                  showtime_id:
                    type: integer
                    format: int32

        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: boolean
        '400':
          description: Operation failed
          content:
            application/json:
              schema:
                type: boolean
                example: false

  /ticket/create:
    post:
      tags:
        - ticket
      description: Tạo các vé mới trong CSDL
      parameters:
        - name: invoice_id
          in: query
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  seat_id:
                    type: integer
                    format: int32
                  showtime_id:
                    type: integer
                    format: int32

        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ticket'
        '400':
          description: Operation failed

  /ticket:
    delete:
      tags:
        - ticket
      description: Xoá vé trong CSDL dựa trên hoá đơn
      parameters:
        - name: invoice_id
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: boolean
        '400':
          description: Operation failed
# ----- Schema definitions  ----------------------------------------
components:
  schemas:
    Ticket:
      type: object
      properties:
        id:
          type: integer
          format: int32
        invoice_id:
          type: integer
          format: int32
        showtime_id:
          type: integer
          format: int32
        seat_id:
          type: integer
          format: int32
        price:
          type: number
          format: float