openapi: 3.0.0
info:
  version: '1.0'
  title: Cinema API
  description: Thông tin chi tiết về các Rest API phục vụ cho demo module Thanh toán đặt vé xem phim online của môn phát triển phần mềm hướng dịch vụ.
tags:
  - name: user

paths:
  # ------- user service -------------------------------------------------------
  /user:
    get:
      tags:
        - user
      description: Lấy thông tin chi tiết của người dùng
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Invalid ID supplied
    put:
      tags:
        - user
      description: Cập nhật thông tin người dùng
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: boolean
        '404':
          description: User ID not found
components:
  # ----- Schema definitions  ----------------------------------------
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int32
        email:
          type: string
          format: email
        username:
          type: string
        password:
          type: string
        amount:
          type: integer
          format: float
      required:
        - id