openapi: 3.0.0
info:
  version: '1.0'
  title: Cinema API
  description: Thông tin chi tiết về các Rest API phục vụ cho demo module Thanh toán đặt vé xem phim online của môn phát triển phần mềm hướng dịch vụ.
tags:
  - name: notification

paths:
  # -------- Task serivce endpoint ------------------------------
  /start:
    post:
      tags:
        - start
      description: Bắt đầu task đặt vé
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: integer
        - name: request_id
          in: query
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  film_showtime_id:
                    type: integer
                    format: int32
                  seat_id:
                    type: integer
                    format: int32
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: boolean
                example: true
        '400':
          description: Operation failed

    get:
      tags:
        - start
      description: Bắt đầu task đặt vé
      parameters:
        - name: request_id
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
                example: [1,1,1,-1,0,0]